# Generated by Django 4.2.11 on 2026-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_url',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Name URL'),
        ),
    ]
