# Generated by Django 4.2.11 on 2026-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0002_course_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_short',
            field=models.CharField(max_length=150, null=True, verbose_name='Короткий опис'),
        ),
    ]
