# Generated by Django 4.2.11 on 2026-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0003_course_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='Опис'),
        ),
    ]
