# Generated by Django 4.2.11 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0006_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description_short',
            field=models.CharField(max_length=250, null=True, verbose_name='Короткий опис'),
        ),
    ]
