# Generated by Django 5.1.6 on 2026-06-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0008_alter_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='Напр. «5 місяців», «3 місяці»', max_length=50, null=True, verbose_name='Тривалість курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='emoji_icon',
            field=models.CharField(blank=True, default='🎮', help_text='Емодзі, що відображається на картці курсу (напр. 🎮, 🐍, 🎨)', max_length=10, verbose_name='Емодзі іконка'),
        ),
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.JSONField(blank=True, help_text='Список питань/відповідей. Приклад: [{"question": "З якого віку?", "answer": "Від 10 років."}]', null=True, verbose_name='Часті запитання (FAQ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='for_whom',
            field=models.JSONField(blank=True, help_text='Список об\'єктів. Приклад: [{"icon": "🎮", "title": "Фанати Roblox", "text": "Хочуть не просто грати, а створювати"}]', null=True, verbose_name='Для кого курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Якщо знято — курс не відображається на сайті', verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість занять'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Початківець'), ('intermediate', 'Середній'), ('advanced', 'Просунутий')], default='beginner', max_length=20, verbose_name='Рівень'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta опис (SEO)'),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_full',
            field=models.CharField(blank=True, help_text='Напр. «11000 грн» або «Макс. знижка»', max_length=50, null=True, verbose_name='Ціна (повна)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_monthly',
            field=models.CharField(blank=True, help_text='Напр. «1200 грн» або «Уточніть»', max_length=50, null=True, verbose_name='Ціна (помісячна)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_semester',
            field=models.CharField(blank=True, help_text='Напр. «6500 грн» або «Знижка»', max_length=50, null=True, verbose_name='Ціна (семестр)'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_modules',
            field=models.JSONField(blank=True, help_text='Список модулів. Приклад: [{"num": "01", "title": "Знайомство з Roblox Studio", "subtitle": "Інтерфейс та перший світ", "topics": ["Інтерфейс редактора", "Перша локація"]}]', null=True, verbose_name='Програма (модулі)'),
        ),
        migrations.AddField(
            model_name='course',
            name='results',
            field=models.JSONField(blank=True, help_text='Список результатів. Приклад: [{"icon": "🏆", "text": "Власна гра у Roblox"}]', null=True, verbose_name='Результати курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, help_text='Напр. «2 заняття на тиждень по 90 хвилин»', max_length=100, null=True, verbose_name='Розклад'),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_projects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Проєктів створено'),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Напр. 4.9', max_digits=3, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_students',
            field=models.PositiveIntegerField(blank=True, help_text='Напр. 120', null=True, verbose_name='Учнів пройшло'),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Років викладаємо'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_will_learn',
            field=models.JSONField(blank=True, help_text='Список рядків. Приклад: ["Основи Lua", "Створення 3D-світів", "Публікація гри"]', null=True, verbose_name='Що вивчить дитина'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата_ціна'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Детальний опис курсу (відображається у секції "Як проходить навчання")', null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_short',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='kid_age',
            field=models.CharField(blank=True, help_text='Напр. «від 10 років» або «8–14 років»', max_length=50, null=True, verbose_name='Вік учня'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, help_text='Залишіть порожнім або вкажіть базову ціну для SEO', max_length=50, null=True, verbose_name='Вартість'),
        ),
    ]
