# Generated by Django 5.1.6 on 2026-07-03 20:08

import Web_1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0009_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images', validators=[Web_1.models.validate_image_size], verbose_name='Картинка'),
        ),
    ]
