# Generated by Django 5.1.6 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0010_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='advantages',
            field=models.JSONField(blank=True, help_text='Список нумерованих переваг курсу/професії. Приклад: [{"title": "Висока затребуваність", "text": "Python — одна з найпопулярніших мов програмування у світі"}]', null=True, verbose_name='Переваги напряму'),
        ),
    ]
