# Generated by Django 4.2.11 on 2026-07-16 20:31

import Web_1.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0011_course_advantages'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Залиште порожнім — згенерується автоматично з заголовка. Використовується у людино-зрозумілому URL новини.', max_length=220, unique=True, verbose_name='URL (slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images', validators=[Web_1.models.validate_image_size], verbose_name='Зображення')),
                ('description_short', models.CharField(help_text='Використовується в анонсі на сторінці "Новини" та як SEO-опис, якщо окремий meta-опис не вказано.', max_length=300, verbose_name='Короткий опис')),
                ('content', models.TextField(help_text='Основний текст. Порожні рядки утворюють нові абзаци.', verbose_name='Текст новини')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('meta_description', models.CharField(blank=True, help_text='Якщо не вказано — використовується короткий опис.', max_length=300, null=True, verbose_name='Meta опис (SEO)')),
                ('is_active', models.BooleanField(default=True, help_text='Якщо знято — новина не відображається на сайті', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-published_date'],
            },
        ),
    ]
