# Generated by Django 5.1.6 on 2026-08-20 06:21

import Web_1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0014_fill_missing_meta_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Будь-який формат (jpg, png, heic тощо) — при збереженні автоматично конвертується у WebP і обрізається під єдиний формат галереї.', upload_to='gallery_images', validators=[Web_1.models.validate_image_size], verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, help_text='Короткий опис фото для пошукових систем і скрінрідерів. Якщо порожньо — використовується загальний опис "Галерея КОДІМ".', max_length=150, verbose_name='Alt-текст (SEO)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Менше число — раніше в каруселі. Фото з однаковим числом сортуються за датою додавання.', verbose_name='Порядок показу')),
                ('is_active', models.BooleanField(default=True, help_text='Якщо знято — фото завантажене, але не відображається в галереї на головній.', verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея (головна сторінка)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
