# Generated by Django 5.1.6 on 2026-07-26 10:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Web_1', '0013_alter_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст питання')),
                ('question_type', models.CharField(choices=[('single', 'Одна правильна відповідь'), ('multiple', 'Кілька правильних відповідей')], default='single', max_length=10, verbose_name='Тип питання')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва матеріалу')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Визначає послідовність проходження (1, 2, 3 ...).', verbose_name='Порядок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст матеріалу')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Посилання на відео (YouTube)')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл (PDF тощо)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Web_1.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Матеріал курсу',
                'verbose_name_plural': 'Матеріали курсу',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Варіант відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.question')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Підсумковий тест', max_length=200, verbose_name='Назва тесту')),
                ('passing_score', models.PositiveSmallIntegerField(default=70, verbose_name='Прохідний бал, %')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Максимум спроб')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Web_1.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Результат, %')),
                ('passed', models.BooleanField(default=False, verbose_name='Складено')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проходження')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='learning.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Призначено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Web_1.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Учень')),
            ],
            options={
                'verbose_name': 'Призначення курсу',
                'verbose_name_plural': 'Призначення курсів',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочитання')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогрес по матеріалу',
                'verbose_name_plural': 'Прогрес по матеріалах',
                'unique_together': {('user', 'material')},
            },
        ),
    ]
