# Generated by Django 5.1.6 on 2026-07-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Відповідь правильна')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='learning.question', verbose_name='Питання')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='learning.testresult', verbose_name='Спроба тесту')),
                ('selected_answers', models.ManyToManyField(blank=True, related_name='+', to='learning.answer', verbose_name='Обрані варіанти')),
            ],
            options={
                'verbose_name': 'Відповідь учня на питання',
                'verbose_name_plural': 'Відповіді учнів на питання',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
