# Generated by Django 6.0.2 on 2026-07-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_1', '0013_alter_news_content'),
        ('learning', '0002_testresultanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='learning.material', verbose_name='Матеріал (урок)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Web_1.course', verbose_name='Курс'),
        ),
    ]
